before_script:
  - apk add --update build-base linux-headers
  - pip install -r requirements.txt
  - pip install flake8
  - cp test/Test.py plugins/
  - cp test/config.json ./
  - sed -i "s/VERSION/$(python -V 2>&1 | awk '{ print $2 }' | sed 's/\./-/g')/" config.json

.test: &test
  only:
    - master
  script:
    - python eleos.py config.json
    - flake8 -v

python-3.3:
  <<: *test
  image: python:3.3-alpine

python-3.4:
  <<: *test
  image: python:3.4-alpine

python-3.5:
  <<: *test
  image: python:3.5-alpine

python-3.6:
  <<: *test
  image: python:3.6-alpine
