before_script:
  - pip install -r requirements.txt
  - cp test/Test.py plugins/
  - cp test/config.json ./
  - sed -i "s/VERSION/$(python -V 2>&1 | awk '{ print $2 }' | sed 's/\./-/g')/" config.json

.test: &test
  script:
    - python eleos.py config.json

python-3.3:
  <<: *test
  image: python:3.3

python-3.4:
  <<: *test
  image: python:3.4

python-3.5:
  <<: *test
  image: python:3.5
